config/routes.rb
Rails.application.routes.draw do
  root 'sites#index'

  get 'login' => 'sessions#new', as: 'login'
  get 'logout' => 'sessions#destroy', as: 'logout'

  # front end
  resources :import_formats, except: [:show, :edit, :update]
  resource :session, only: [:new, :create, :destroy]
  resources :sites do
    member { get :pixel }
    resources :imports, except: [:edit, :update]
    resources :tracking_links
  end
  resources :users, except: [:show]

  namespace :api do
    resources :sites, only: [] do
      member do
        get :graph, :table
      end
    end
  end

  # redirects / tracking
  namespace :track do
    resources :visits
    resources :conversions
  end

  get 'r/:token', to: 'track/visits#new'

  if Rails.env.development?
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/import_format.rb
class ImportFormat < ActiveRecord::Base
  has_many :imports

  validates :file_type, presence: true
  validates :date_column, presence: true
  validates :url_column, presence: true
  validates :cost_column, presence: true
end

app/controllers/import_formats_controller.rb
require 'csv'

class ImportFormatsController < ApplicationController
  before_action :require_user, :require_admin

  def index
    @import_formats = ImportFormat.all
  end

  def new
    @import_format = ImportFormat.new
    @import = Import.includes(:site).find(params[:import_id])
    @site = @import.site
  end

  def create
    @import_format = ImportFormat.new(import_format_params)
    @import = Import.includes(:site).find(params[:import_id])
    @site = @import.site

    if @import_format.save
      @import.update_attribute(:import_format_id, @import_format.id) # triggers after_commit
      redirect_to [@site, @import]
    else
      render :new
    end
  end

  def destroy
    import_format = ImportFormat.find(params[:id])
    import_format.destroy
    redirect_to import_formats_path, notice: "Import Format deleted"
  end

  private

  def import_format_params
    columns = params[:columns]
      .find_all { |k, v| v.present? } # find non-empty values: [["0", "date_column"], ["6", "url_column"], ["17", "cost_column"]]
      .map { |e| [e[1], e[0]] } # flip array elements
      .flatten # flatten the array: ["date_column", "0", "url_column", "6", "cost_column", "17"]
    Hash[*columns].merge file_type: params[:import_format][:file_type] # turn into hash and merge file_type param
  end
end

app/views/import_formats/index.html.erb
<%= page_title "Import Formats" %>

<% if @import_formats.empty? %>
  <div class="alert alert-block alert-warning">
    <h4>No import formats found.</h4>
    <p>To add an import format, go to a Site, then click "Cost Imports" and upload a new file.</p>
  </div>
<% else %>
  <table class="table">
    <thead>
      <tr>
        <th>File Type</th>
        <th>Date Column</th>
        <th>URL Column</th>
        <th>Cost Column</th>
        <th></th>
      </tr>
    </thead>
    <% @import_formats.each do |import_format| %>
      <tr>
        <td><%= gicon "file" %> <%= import_format.file_type %></td>
        <td class="text-muted"><%= import_format.date_column %></td>
        <td class="text-muted"><%= import_format.url_column %></td>
        <td class="text-muted"><%= import_format.cost_column %></td>
        <td class="txtr"><%= link_to "Delete", import_format_path(import_format), method: :delete, data: { confirm: "Are you sure you want to delete this import format?" }, class: "btn btn-danger btn-sm" %></td>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/import_formats/new.html.erb
<%= page_title "Setup a New Import Format" %>

<div class="alert alert-block alert-info">
  <p>Below are the first 10 lines of the file you imported. Please select the Date, Destination URL, and Cost columns.</p>
</div>

<%= bootstrap_form_for @import_format do |f| %>
  <%= f.alert_message "Please fix the following errors and ensure that you've selected Date, Destination URL, and Cost columns" %>

  <%= hidden_field_tag :import_id, params[:import_id] %>
  <div class="row">
    <div class="col-md-5">
      <%= f.text_field :file_type, help: "Example: Adwords CSV" %>
    </div>
  </div>

  <table class="table table-bordered">
    <tr>
      <% @import.first_line.each_with_index do |cell, i| %>
        <td><%= select_tag "[columns][#{i}]", options_for_select([["Date", "date_column"], ["Destination URL", "url_column"], ["Cost", "cost_column"]]), include_blank: true %></td>
      <% end %>
    <tr>
    <% @import.preview.each do |line| %>
      <tr>
        <% line.each do |cell| %>
          <td><%= cell %></td>
        <% end %>
      </tr>
    <% end %>
  </table>

  <%= f.primary "Save Format" %>
  <%= link_to "Cancel and Delete Import", site_import_path(@site, @import), method: :delete, data: { confirm: "Are you sure you want to delete this import?" }, class: "btn btn-danger" %>
<% end %>