config/routes.rb
Rails.application.routes.draw do
  root 'sites#index'

  get 'login' => 'sessions#new', as: 'login'
  get 'logout' => 'sessions#destroy', as: 'logout'

  # front end
  resources :import_formats, except: [:show, :edit, :update]
  resource :session, only: [:new, :create, :destroy]
  resources :sites do
    member { get :pixel }
    resources :imports, except: [:edit, :update]
    resources :tracking_links
  end
  resources :users, except: [:show]

  namespace :api do
    resources :sites, only: [] do
      member do
        get :graph, :table
      end
    end
  end

  # redirects / tracking
  namespace :track do
    resources :visits
    resources :conversions
  end

  get 'r/:token', to: 'track/visits#new'

  if Rails.env.development?
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/site.rb
class Site < ActiveRecord::Base
  has_many :conversions, through: :visits
  has_many :imports
  has_many :tracking_links
  has_many :visits, through: :tracking_links

  validates :name, presence: true

  def to_s
    name
  end
end

app/controllers/api/sites_controller.rb
class Api::SitesController < ApplicationController
  before_action :require_user

  def graph
    site = Site.find(params[:id])
    stats = SiteDailyActivity.new(site, current_user.time_zone, params[:start_date], params[:end_date], params[:filters]).query
    render json: SiteGraphPresenter.new(params[:start_date], params[:end_date], stats).data.to_json
  end

  def table
    site = Site.find(params[:id])
    aggregate_by = params[:aggregate_by]
    aggregate_by = "medium" if aggregate_by == "media"
    stats = SitePerformanceAggregator.new(site, current_user.time_zone, params[:start_date], params[:end_date], aggregate_by, params[:filters]).query
    render json: SiteTablePresenter.new(stats).data.to_json
  end
end

app/controllers/data/sites_controller.rb
class Data::SitesController < ApplicationController
  before_action :require_user

  def visits_and_conversions
    site = Site.find(params[:id])
    chart = VisitsAndConversionsChart.new(site, current_user.time_zone)
    render json: chart.data.to_json
  end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  before_action :require_user
  before_action :require_admin, except: [:index, :show]

  def index
    @sites = sites
  end

  def new
    @site = Site.new
  end

  def create
    @site = Site.new(site_params)
    if @site.save
      redirect_to @site, notice: "#@site has been added"
    else
      render :new
    end
  end

  def show
    @site = Site.find(params[:id])
    @visits = @site.visits.includes(:tracking_link, :conversion)
    @start_date = Date.parse(params[:start_date]) rescue default_start_date
    @end_date = Date.parse(params[:end_date]) rescue default_end_date
    @aggregate_by = params[:aggregate_by] || default_aggregate_by
    @filters = params[:filters]
  end

  def pixel
    @site = Site.find(params[:id])
  end

  def edit
    @site = Site.find(params[:id])
  end

  def update
    @site = Site.find(params[:id])
    if @site.update_attributes(site_params)
      redirect_to @site, notice: "#@site has been updated"
    else
      render :edit
    end
  end

  def destroy
    site = Site.find(params[:id])
    site.destroy
    redirect_to sites_path, notice: "#{site} has been deleted"
  end

  private

  def default_aggregate_by
    "media"
  end

  def default_start_date
    Time.now.in_time_zone(User.first.time_zone).to_date - 29.days
  end

  def default_end_date
    Time.now.in_time_zone(User.first.time_zone).to_date
  end

  def site_params
    params.require(:site).permit(:name)
  end
end

app/views/sites/_form.html.erb
<div class="row">
  <div class="col-md-4">
    <%= bootstrap_form_for site do |f| %>
      <%= f.alert_message "Please fix the error below" %>

      <%= f.text_field :name, help: (site.persisted? ? "" : "Example: My Website") %>
      <%= f.primary %>
      <% if site.persisted? %>
        <%= link_to "Cancel", site, class: "btn btn-default" %>
      <% else %>
        <%= link_to "Cancel", sites_path, class: "btn btn-default" %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/sites/_tabs.html.erb
<% if current_user.admin? %>
  <ul class="nav nav-tabs">
    <li <%= %{class="active"}.html_safe if active == :site %>><%= link_to site, @site %></li>
    <li <%= %{class="active"}.html_safe if active == :tracking_links %>><%= link_to "Tracking Links", site_tracking_links_path(@site) %></li>
    <li <%= %{class="active"}.html_safe if active == :pixel %>><%= link_to "Conversion Code", pixel_site_path(@site) %></li>
    <li <%= %{class="active"}.html_safe if active == :imports %>><%= link_to "Cost Imports", site_imports_path(@site) %></li>
    <li <%= %{class="active"}.html_safe if active == :edit %>><%= link_to "Edit Site", edit_site_path(@site) %></li>
  </ul>
<% end %>

app/views/sites/edit.html.erb
<%= title "Edit Site" %>

<%= render "sites/tabs", site: @site, active: :edit %>

<%= link_to "Delete Site", site_path(@site), method: :delete, data: { confirm: "Are you sure you want to delete this site?\n\nWARNING: Your tracking links will continue to redirect, but you will no longer be able to view stats." }, class: "btn btn-danger pull-right" %>

<%= render "form", site: @site %>

app/views/sites/index.html.erb
<%= page_title "Sites" %>

<%= link_to "New Site", new_site_path, class: "btn btn-primary new-site" if current_user.admin? %>

<% unless @sites.empty? %>
  <table class="table">
    <% @sites.each do |site| %>
      <tr>
        <td><%= gicon "stats" %> <%= link_to site, site %></td>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/sites/new.html.erb
<%= page_title "New Site" %>

<%= render "form", site: @site %>

app/views/sites/pixel.html.erb
<%= title "#@site Conversion Code" %>

<%= render "sites/tabs", site: @site, active: :pixel %>

<div class="site-conversion-code">
  <p>First, enter the amount of revenue you expect from a conversion:
  <div class="row">
    <div class="col-md-2">
      <form>
        <div class="input-group">
          <span class="input-group-addon">$</span>
          <input class="form-control" type="text" value="4.99">
        </div>
      </form>
    </div>
  </div>

  <p>Then, copy and paste the following code into the &lt;body&gt; of your conversion or success page.<p>

  <div class="well well-sm">
    &lt;img src="<%= ENV['HTTP_HOST'] %>/track/conversions?revenue=<span>4.99</span>" width="1" height="1"&gt;
  </div>
</div>

app/views/sites/show.html.erb
<%= title @site %>

<% content_for :javascript do %>
  <%= javascript_tag "App.SiteStatsController.setup();" %>
<% end %>

<%= render "sites/tabs", site: @site, active: :site %>

<div class="well well-sm site-report-controls">
  <div class="clearfix">
    <div class="date-display">
      <a href="#"><%= gicon "calendar" %> <span class="start-date"><%= @start_date.to_s(:american_date) %></span> to <span class="end-date"><%= @end_date.to_s(:american_date) %></span> <b class="caret"></b></a>
    </div>
    <div class="date-selectors hide">
      <button type="button" class="close">&times;</button>
      <div class="pickers">
        <input type="text" id="start-date" value="<%= @start_date.to_s(:american_date) %>" class="form-control date-picker">
        to
        <input type="text" id="end-date" value="<%= @end_date.to_s(:american_date) %>" class="form-control date-picker">
        <button class="btn btn-default">Apply</button>
      </div>
      <hr>
      <div class="shortcuts">
        <div>
          <a href="#" data-date-shortcut="today">Today</a>
          <a href="#" data-date-shortcut="yesterday">Yesterday</a>
          <a href="#" data-date-shortcut="last-7-days">Last 7 Days</a>
        </div>
        <div>
          <a href="#" data-date-shortcut="last-30-days">Last 30 Days</a>
          <a href="#" data-date-shortcut="this-month">This Month</a>
          <a href="#" data-date-shortcut="last-month">Last Month</a>
        </div>
      </div>
    </div>
    <ul class="aggregate-by nav nav-pills">
      <li <%= %{class="active"}.html_safe if @aggregate_by == "media" %>><a href="#" data-aggregate-by="media">Media</a></li>
      <li <%= %{class="active"}.html_safe if @aggregate_by == "source" %>><a href="#" data-aggregate-by="source">Source</a></li>
      <li <%= %{class="active"}.html_safe if @aggregate_by == "campaign" %>><a href="#" data-aggregate-by="campaign">Campaign</a></li>
      <li <%= %{class="active"}.html_safe if @aggregate_by == "ad_content" %>><a href="#" data-aggregate-by="ad_content">Ad Content</a></li>
      <li <%= %{class="active"}.html_safe if @aggregate_by == "keyword" %>><a href="#" data-aggregate-by="keyword">Keyword</a></li>
      <li <%= %{class="active"}.html_safe if @aggregate_by == "sid" %>><a href="#" data-aggregate-by="sid">SID</a></li>
    </ul>
  </div>

  <div class="filters">
    <% @filters && @filters.each do |filter| %>
      <span data-filter-type="<%= filter[0] %>" data-filter="<%= filter[1] %>" class="label label-primary">
        <%= filter[0].gsub /_/, ' ' %>: <%= filter[1] %>
        <a href="#">&times;</a>
      </span>
    <% end %>
  </div>
</div>

<div class="site-graph" data-url="<%= graph_api_site_path(@site) %>">
  <div class="alert alert-info site-loading">Loading data...</div>
</div>

<table class="table site-table" data-url="<%= table_api_site_path(@site) %>">
  <thead>
    <tr>
      <th class="aggregate-by"></th>
      <th>Visits</th>
      <th>Conversions</th>
      <th>Conversion Rate</th>
      <th class="money">Cost</th>
      <th class="money">Revenue</th>
      <th class="money">Profit</th>
      <th class="money"><span data-toggle="tooltip" title="Cost Per Visit">CPV <%= gicon "info-sign" %></span></th>
      <th class="money"><span data-toggle="tooltip" title="Revenue Per Visit">RPV <%= gicon "info-sign" %></span></th>
      <th class="money"><span data-toggle="tooltip" title="Customer Acquisition Cost">CAC <%= gicon "info-sign" %></span></th>
      <th class="money"><span data-toggle="tooltip" title="Revenue Per User">RPU <%= gicon "info-sign" %></span></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td colspan="11">
        <div class="alert alert-info site-loading">Loading data...</div>
      </td>
    </tr>
  </tbody>
  <tfoot>
  </tfoot>
</table>

<script type="text/html" id="site-table-row-template">
  <tr>
    <td class="name">
      <div>
        <a href="#" data-filter-type="<%%= type %>" data-filter="<%%= name %>"><%%= name %></a>
      </div>
    </td>
    <td class="number"><%%= visits %></td>
    <td class="number"><%%= conversions %></td>
    <td class="txtr"><%%= conversion_rate %>%</td>
    <td class="money">$<%%= cost %></td>
    <td class="money">$<%%= revenue %></td>
    <td class="money profit">$<%%= profit %></td>
    <td class="money">$<%%= cost_per_visit %></td>
    <td class="money">$<%%= revenue_per_visit %></td>
    <td class="money">$<%%= cost_per_conversion %></td>
    <td class="money">$<%%= revenue_per_conversion %></td>
  </tr>
</script>

<script type="text/html" id="site-filter-template">
  <span data-filter-type="<%%= type %>" data-filter="<%%= filter %>" class="label label-primary">
    <%%= type_display %>: <%%= filter %>
    <a href="#">&times;</a>
  </span>
</script>