config/routes.rb
Rails.application.routes.draw do
  root 'sites#index'

  get 'login' => 'sessions#new', as: 'login'
  get 'logout' => 'sessions#destroy', as: 'logout'

  # front end
  resources :import_formats, except: [:show, :edit, :update]
  resource :session, only: [:new, :create, :destroy]
  resources :sites do
    member { get :pixel }
    resources :imports, except: [:edit, :update]
    resources :tracking_links
  end
  resources :users, except: [:show]

  namespace :api do
    resources :sites, only: [] do
      member do
        get :graph, :table
      end
    end
  end

  # redirects / tracking
  namespace :track do
    resources :visits
    resources :conversions
  end

  get 'r/:token', to: 'track/visits#new'

  if Rails.env.development?
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/views/layouts/_alerts.html.erb
<div class="alerts">
  <% if flash[:alert] %>
    <div class="alert alert-error"><%= flash[:alert] %></div>
  <% end %>
  <% if flash[:notice] %>
    <div class="alert alert-success"><%= flash[:notice] %></div>
  <% end %>
</div>

app/views/layouts/_favicons.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="/apple-touch-icon-57x57.png">
<link rel="apple-touch-icon" sizes="114x114" href="/apple-touch-icon-114x114.png">
<link rel="apple-touch-icon" sizes="72x72" href="/apple-touch-icon-72x72.png">
<link rel="apple-touch-icon" sizes="144x144" href="/apple-touch-icon-144x144.png">
<link rel="apple-touch-icon" sizes="60x60" href="/apple-touch-icon-60x60.png">
<link rel="apple-touch-icon" sizes="120x120" href="/apple-touch-icon-120x120.png">
<link rel="apple-touch-icon" sizes="76x76" href="/apple-touch-icon-76x76.png">
<link rel="apple-touch-icon" sizes="152x152" href="/apple-touch-icon-152x152.png">
<link rel="icon" type="image/png" href="/favicon-196x196.png" sizes="196x196">
<link rel="icon" type="image/png" href="/favicon-160x160.png" sizes="160x160">
<link rel="icon" type="image/png" href="/favicon-96x96.png" sizes="96x96">
<link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32">
<link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="msapplication-TileImage" content="/mstile-144x144.png">

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-fixed-top navbar-inverse" role="navigation">
  <div class="container">
    <a class="navbar-brand" href="/"><img src="<%= image_path "logo.png" %>" height="20"> <span>Track Simply</span></a>
    <ul class="nav navbar-nav pull-right">
      <% if current_user %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Sites <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <% sites.each do |site| %>
              <li><%= link_to gicon("stats", site), site %></li>
            <% end %>
            <% if current_user.admin? %>
              <% unless sites.empty? %>
                <li class="divider"></li>
              <% end %>
              <li><%= link_to gicon("plus", "New Site"), new_site_path %></li>
            <% end %>
          </ul>
        </li>
        <% if current_user.admin? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Settings <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to gicon("user", "Users"), users_path %></li>
              <li><%= link_to gicon("file", "Import Formats"), import_formats_path %></li>
            </ul>
          </li>
        <% end %>
        <li><%= link_to "Log Out", logout_path %></li>
      <% else %>
        <li><%= link_to "Log In", login_path %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Track Simply <%= yield(:title) %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
    <link href="http://fonts.googleapis.com/css?family=Lily+Script+One" rel="stylesheet" type="text/css">
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render "layouts/favicons" %>
  </head>
  <body>
    <%= render "layouts/navbar" %>
    <div class="main">
      <div class="container">
        <%= render "layouts/alerts" %>
        <%= yield %>
      </div>
    </div>
    <%= yield :javascript %>
  </body>
</html>